### ISSUE TITLE
How to get started with this bomberland environment?

### ISSUE THREAD

**Issue by GuibinChenTHU** [CoderOneHQ/bomberland#60]
Dear author: Currently I plan to participate the bomberland competition but I fail in the "Getting started" stage. I have downloaded the repo of the environment and installed Docker in my MacPro, then I copy the order "docker-compose up --abort-on-container-exit --force-recreate" into the terminal, but it fails  and shows the error: "Can't find a suitable configuration file in this directory or any  parent. Are you in the right directory? 
       Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml"
Can you give me some advices on how to smoothly get started the game? Appreciate!

**Comment by thegalah** [comment]
I believe the issue may be that you are in the incorrect directory and there is no compose file in the directory you are attempting to run those commands.
Can you check the contents of the directory you are in, by running `ls` ?
Can you also check your current working directory by running `pwd`?

**Comment by GuibinChenTHU** [comment]
THX for your warmly reply! I excuted the "docker-compose up" in the terminal after export the PATH=folder path, but it turned out that such implementation didn't work. I try another way: build new terminal right on the folder and excute the same order. Now it works! thx very much. Before I was confused that why error still happens after export the very path of the folder,&nbsp; it should be the same as building new termina on the folder&nbsp; &nbsp;


Best Regards,
Jeremy



---Original---
From: ***@***.***&gt;
Date: Sun, Dec 19, 2021 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CoderOneHQ/bomberland] How to get started with this bomberlandenvironment? (Issue #60)




 
I believe the issue may be that you are in the incorrect directory and there is no compose file in the directory you are attempting to run those commands.
 Can you check the contents of the directory you are in, by running ls ?
 Can you also check your current working directory by running pwd?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thegalah** [comment]
Perfect glad that helped!
