### ISSUE TITLE
How to train the agent in PC locally?

### ISSUE THREAD

**Issue by GuibinChenTHU** [CoderOneHQ/bomberland#62]
Dear author: I'm wondering if we are only permitted to train our RL agent by connecting the game server via docker? Then how we check the bugs in our agent.py file? In general, there will be some inevitable errors in setting up program of RL agent for the environment. It can be more convenient for us to debug if we are provided with the environment.py file in the process of developing RL agent file. If we are not permitted to do this, then how we check if our submitted agent.py file has no errors?
Looking forward for your reply!

**Comment by thegalah** [comment]
You are permitted to train in any way you would like. You do not have to use docker to train you can use one of the binaries provided.

To test your agent.py works you can build it into a docker image tagged locally and run your agent from that image. Feel free to reach out to me directly on discord if you need any help
