### ISSUE TITLE
Typo in word "instantiate" in line 81 of bomberland/engine/bomberland-engine/src/Game/Entity/World/createWorld/createWorldFromSeed/createWorldFromSeed.ts

### ISSUE THREAD

**Issue by 18goldr** [CoderOneHQ/bomberland#98]
It's spelled as "instantitate" instead of "instantiate".

Not a big deal at all, just figured id let you know lol.

**Comment by thegalah** [comment]
Good spot
https://github.com/CoderOneHQ/bomberland/pull/99
